api_platform:
    title: 'Picorez REST API'
    description: 'A Symfony API to manage a mobile application'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    formats:
        json:
            mime_types: [ 'application/json' ]
    swagger:
        versions: [3]
    enable_swagger_ui: false
    defaults:
        pagination_enabled: false